image: node:latest

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/

test:
  script:
    - npm install
    - npm test

deploy:
  stage: deploy
  script:
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
